src/lib.rs
Am i missing something else that I need to do? Pretty sure this is all...
closes #33.
=> make UUid impl Copy, derive Clone

src/lib.rs
This was the source of a hell of a bug... :)
=> Propagate errors when decoding instead of panicking

src/lib.rs
This should have no functional changes, it simply reformats the code with the [rustfmt tool](https://github.com/nrc/rustfmt).
This goes along with the some of the work going on in rust. http://www.ncameron.org/blog/rustfmt-ing-rust/
=> formatted code with rustfmt

src/lib.rs
This adds two tests to address #48.
=> test: ensure formatting compatibility

src/lib.rs
=> Fix index out of bounds panic in parse_str

.travis.yml, Cargo.toml, src/lib.rs
Rebased https://github.com/rust-lang-nursery/uuid/pull/35
=> uuid v5 implementation

Cargo.toml, src/serde.rs
Serde 0.9 has some breaking changes in its traits. This pull request is an effort to make this library compatible with `serde` again.
=> Upgrade to serde 0.9

README.md, src/lib.rs
I got a bit confused about which version I should install when looking at the docs, hopefully this will help the next person :smile:
=> Update version numbers in docs to 0.4

.travis.yml, Cargo.toml, src/lib.rs
support for rfc 4122 uuids (hashed by md5)
addresses #71
=> support v3 UUIDs

src/lib.rs
Not sure if this is useful, just for API completeness.
=> Add impl fmt::{UpperHex,LowerHex} for {Uuid,Hyphenated,Simple}

.travis.yml, bors.toml
=> Add support for borsNG bot

README.md
This fixes #122 
Added Appveyor build status button to the README file and linked the button to https://ci.appveyor.com/project/KodrAus/uuid
=> Added Appveyor build status button to the README file

src/serde.rs
This somehow was missed in #130
=> remove extern crate std in serde

Cargo.toml
References #132 
Continuation of #135
=> bumped toml file to 0.6.0-beta

Cargo.toml
Added authors & fixed the repository links in `cargo.toml`
=> updated toml to reflect uuid repo changes

CODEOWNERS
Reference: https://github.com/orgs/uuid-rs/teams/uuid/discussions/1
=> Bors patch

Cargo.toml, LICENSE-MIT, README.md, src/lib.rs
=> bump from beta to stable

Cargo.toml
=> released package as 0.6.1

.travis.yml
Removed running clippy tests until further notice.
Currently our builds break every night with caching enabled on nightly channel where clippy tests are done.
N/A
N/A
=> Temporarily disable clippy

Cargo.toml
Items left to do for 0.6.2 release:
Reference: #179
=> 0.6.2 release update

Cargo.toml
Items left to do for 0.6.3 release:
Reference: #194
=> 0.6.3 release

src/lib.rs, src/v5.rs
Refactor the v5 impl into its own module
Part of the refactor process
All passing
#124
=> move v5 impl into its own module

src/lib.rs
Remove `Uuid::new` function and relevant tests
`Uuid::new` is slightly unsafe since it  has different behavior depending on the features enabled and the library user not checking for other results. `Uuid::new_*` should instead be used.
Remove test for `Uuid::new`
#176
=> remove `Uuid::new` function

.github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/feature
=> Use new github templates

Cargo.toml
Fixes https://github.com/uuid-rs/uuid/issues/223.
Marking WIP until https://github.com/integer32llc/rust-playground/pull/326 has landed.
=> Use custom metadata to specify playground features

.travis.yml, src/core_support.rs, src/lib.rs
Fixes rustfmt with new changes
Rustfmt removed `write-mode` from cli options
No changes required
[rustfmt commit](https://github.com/rust-lang-nursery/rustfmt/commit/5d9f5aa05a668e7dfef87b46d89dad2884df9d41) and [issue](https://github.com/rust-lang-nursery/rustfmt/issues/1976)
=> fix fmt diff for CI 

COPYRIGHT, src/adapter.rs, src/core_support.rs, src/lib.rs, src/prelude.rs, src/serde_support.rs, src/slog_support.rs, src/std_support.rs, src/test_util.rs
* Add a `COPYRIGHT` file
* Add the license header to all `.rs` files, not just `lib.rs`
N/A
N/A
N/A
=> Add COPYRIGHT file and add license headers to all rs files

src/lib.rs
Change more functions to use `const_fn` feature
Compile time evalution \o/
Current tests passing
#232 #226
=> add more `const fn`s

.travis.yml, Cargo.toml
* Clean up `Cargo.toml`
* fix `const-fn` -> `const_fn`
Clarity
N/A
N/A
=> Cargo cleanups

Cargo.toml
=> Release: 0.6.4

src/lib.rs
Fix the feature names 
@kinggoesgaming forgot it
No change 
#228
=> fix feature name

Cargo.toml
=> prepare 0.6.5

Cargo.toml, src/v4.rs
Update `rand` to `0.5` and refactor code accordingly
Regular dependency updates
Curent tests passing
supersedes #258
=> update rand to 0.5.x

.github/PULL_REQUEST_TEMPLATE.md
=> new pull request template

README.md
**I'm submitting a(n)** enhancement
Mentions MSRV of 1.22 on readme
closes #275
=> Add min rust version to readme

CODE_OF_CONDUCT.md, src/lib.rs
- changed the email to report@uuid-rs.groups.io
- added a statement to refer to the latest version of CoC
=> update code of conduct

src/lib.rs, src/std_support.rs
This was accidental. Oops
#286
=> revert removal of std::error::Error impl for uuid::BytesError

Cargo.toml, README.md, src/lib.rs
**I'm submitting a(n)** release
0.7.0-beta release
#306
=> beta release

Cargo.toml, README.md, src/lib.rs
**I'm submitting a(n)** (release)
0.7 release
not needed
=> prepare for 0.7 release

README.md
Fixes the documentation in the readme for the 0.7 release
=> Update readme for 0.7

src/adapter/mod.rs, src/lib.rs, src/prelude.rs, src/v1.rs
Fix the doc names from `Uuid*` to `*`, so that the links work.
=> fix up the doc names to follow the name changes

Cargo.toml
**I'm submitting a(n)** (release)
#318
=> prepare for 0.7.1 release

src/adapter/mod.rs, src/builder.rs, src/v4.rs
Used clippy on stable channel for most features (except guid, since I don't have windows available)
Will be creating another PR that closes #282. But wanted to catch the current issues before doing that
Current tests pass. No new tests needed
N/A
=> Cleanup the code

.travis.yml, src/lib.rs
Finally reenabled `clippy` :)
`clippy` is now provided as a component.
Tests should pass.
closes #282
=> reenable clippy

src/adapter/compact.rs
We don't actually need to provide our own implementation of serializing a 16-byte array because `serde` has one already we can lean on.
=> Use provided serde impls for compact serialization

Cargo.toml, src/lib.rs
=> update Cargo.toml and lib.rs for 0.7.2 release

Cargo.toml, README.md, src/lib.rs
**I'm submitting a(n)** release prep
0.7.3
#381
=> prepare files for 0.7.3 release

Cargo.toml
Fixes the docs.rs build
People like docs
N/A
N/A
=> fix docs.rs

Cargo.toml, README.md, src/lib.rs
**I'm submitting a(n)** release prep
update files for 0.7.4 
Lets fix dem docs
N/A
#386
=> prep for 0.7.4

Cargo.toml
Add the categories and keywords in the `Cargo.toml`
Complete Documentation -> C-METADATA requirement
N/A
#191 -> (C-METADATA)
=> add the categories and keywords

Cargo.toml, README.md, src/lib.rs
Includes #434 
There aren't any code changes in this release, it just includes some additional documentation.
=> Prepare for 0.8.1 release

.github/workflows/ci.yml
**I'm submitting a(n)** meta
The initial move to github actions for CI completely
Travis CI is broken for us for a while now and its best to switch.
------ TODO
#484
=> Create initial ci file

.travis.yml
=> remove fmt from travis

src/v1.rs
Signed-off-by: karthik.n <karthik.n@zohocorp.com>
**I'm submitting a(n)** (other)
This PR fixes the wrong date mentioned in comment.
=> v1: fixed wrong date in comment

Cargo.toml, README.md, src/lib.rs
Includes:
- #504 
- #505 
- #506
=> prepare for 0.8.2 release

CODE_OF_CONDUCT.md
=> update contact details in the CoC

src/v3.rs, src/v5.rs
Please accept this modest typo fix.
=> Fix documentation typo

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
=> Prepare for 1.1.1 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
=> Prepare for 1.1.2 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
=> Prepare for 1.2.1 release

src/error.rs, src/external/serde_support.rs, src/macros.rs
This is a slight adjustment of the error message, since it is contradicting itself.
#655
=> Fix error message.

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* Update syn requirement from 1.0.80 to 2.0.5 by @dependabot in https://github.com/uuid-rs/uuid/pull/663
* Update windows-sys requirement from 0.45.0 to 0.48.0 by @dependabot in https://github.com/uuid-rs/uuid/pull/665
* remove some extra chars in a comment by @KodrAus in https://github.com/uuid-rs/uuid/pull/666
=> Prepare for 1.3.1 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* Create SECURITY.md by @KodrAus in https://github.com/uuid-rs/uuid/pull/668
* Faster as_u128 and to_u128_le by @pkoenig10 in https://github.com/uuid-rs/uuid/pull/669
* @pkoenig10 made their first contribution in https://github.com/uuid-rs/uuid/pull/669
=> prepare for 1.3.2 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* Add `wasm32-wasi` support with tests by @acfoltzer in https://github.com/uuid-rs/uuid/pull/677
* Fix up MSRV build in CI by @KodrAus in https://github.com/uuid-rs/uuid/pull/679
* fix: keep the order when filling random bytes by @Hanaasagi in https://github.com/uuid-rs/uuid/pull/682
=> Prepare for 1.3.4 release

src/timestamp.rs
=> Fixing issue with Cloudflare Workers and wasm32-unknown-unknown when using now()

.github/workflows/ci.yml, Cargo.toml, src/external.rs, src/external/borsh_support.rs, src/lib.rs
Fixes #685
I ended up implementing this for my temporary fork anyway, so thought I'd post it here in case there's interest in adding it back to uuid.
=> Add `borsh` support

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* Fixed wasm tests not running due to incorrect attribute target by @kmusick in https://github.com/uuid-rs/uuid/pull/688
* Fixing issue with Cloudflare Workers and wasm32-unknown-unknown when using now() by @kmusick in https://github.com/uuid-rs/uuid/pull/690
* Add `borsh` support by @grovesNL in https://github.com/uuid-rs/uuid/pull/686
* Fix some timestamp generation by @KodrAus in https://github.com/uuid-rs/uuid/pull/691
=> Prepare for 1.4.0 release

src/lib.rs
For #699 
cc @Jeremiah-Griffin
Is this sufficient for the Diesel use-case you mentioned? We can't add `From<Vec<u8>> for Uuid`, but we can do `TryFrom<Vec<u8>> for Uuid`.
=> Support converting between Uuid and vec

.github/workflows/ci.yml, Cargo.toml, src/lib.rs
This pull request adds support for the `bytemuck` crate, hence fixing my earlier feature request, issue #710.
=> Added `bytemuck` support

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* Add impl From<Uuid> for String under the std feature flag by @brahms116 in https://github.com/uuid-rs/uuid/pull/700
* Remove dead link to templates by @KodrAus in https://github.com/uuid-rs/uuid/pull/704
* make ClockSequence wrap correctly by @fef1312 in https://github.com/uuid-rs/uuid/pull/705
* Track MSRV in Cargo.toml by @KodrAus in https://github.com/uuid-rs/uuid/pull/706
* Support converting between Uuid and vec by @KodrAus in https://github.com/uuid-rs/uuid/pull/703
* Replace MIPS with Miri and add clippy to CI by @KodrAus in https://github.com/uuid-rs/uuid/pull/712
* Added `bytemuck` support by @John-Toohey in https://github.com/uuid-rs/uuid/pull/711
=> Prepare for 1.5.0 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* doc: fix links in v6 module by @metalalive in https://github.com/uuid-rs/uuid/pull/714
* Stabilize UUIDv6-v8 support by @KodrAus in https://github.com/uuid-rs/uuid/pull/718
* @metalalive made their first contribution in https://github.com/uuid-rs/uuid/pull/714
=> Prepare for 1.6.0 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs, src/macros.rs
=> Fix uuid macro in consts

Cargo.toml, src/external.rs, src/external/borsh_support.rs, src/lib.rs
I checked manually that even with borsh =v1.0.0 the tests pass.
=> Upgrade borsh unstable dependency to v1.0 and make it stable

.github/workflows/ci.yml
Looks like our CI builds might have started failing so I'll get them back to good.
=> Fix up CI builds

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* docs: fix small spelling mistake by @bengsparks in https://github.com/uuid-rs/uuid/pull/737
* serde serialize_with support by @dakaizou in https://github.com/uuid-rs/uuid/pull/735
* Fix up CI builds by @KodrAus in https://github.com/uuid-rs/uuid/pull/744
* Only add `wasm-bindgen` as a dependency on `wasm32-unknown-unknown` by @emilk in https://github.com/uuid-rs/uuid/pull/738
* impl AsRef<Uuid> for Uuid by @koshell in https://github.com/uuid-rs/uuid/pull/743
* Add v6 to v8 draft link to README by @KodrAus in https://github.com/uuid-rs/uuid/pull/746
* Add a workflow for running cargo outdated by @KodrAus in https://github.com/uuid-rs/uuid/pull/745
* @bengsparks made their first contribution in https://github.com/uuid-rs/uuid/pull/737
* @dakaizou made their first contribution in …
=> Prepare for 1.8.0 release

src/v7.rs
This just fills in another test gap to make sure the v7 handle values at their upper bounds. The `NoContext` tests already cover the lower bounds.
=> Ensure v7 methods don't overflow on max values

Cargo.toml, README.md, macros/Cargo.toml, src/builder.rs, src/lib.rs, src/timestamp.rs
* Upgrade zerocopy to 0.8 by @yotamofek in https://github.com/uuid-rs/uuid/pull/771
=> Prepare for 1.11.0 release

.github/workflows/ci.yml, Cargo.toml, src/v7.rs
=> Finish cut off docs

Cargo.toml, README.md, macros/Cargo.toml, src/builder.rs, src/lib.rs, src/timestamp.rs
* Finish cut off docs by @KodrAus in https://github.com/uuid-rs/uuid/pull/777
* Fix links in CONTRIBUTING.md by @jacobggman in https://github.com/uuid-rs/uuid/pull/778
* Update rust toolchain before building by @KodrAus in https://github.com/uuid-rs/uuid/pull/781
=> Prepare for 1.11.1 release

Cargo.toml, README.md, macros/Cargo.toml, src/builder.rs, src/lib.rs, src/timestamp.rs
* feat: Add `NonZeroUuid` type for optimized `Option<Uuid>` representation by @ab22593k in https://github.com/uuid-rs/uuid/pull/779
* Finalize `NonNilUuid` by @KodrAus in https://github.com/uuid-rs/uuid/pull/783
=> Prepare for 1.12.0 release

Cargo.toml, README.md, macros/Cargo.toml, src/lib.rs
* Fix links to namespaces in documentation by @cstyles in https://github.com/uuid-rs/uuid/pull/789
* use inherent to_be_bytes and to_le_bytes methods by @Vrtgs in https://github.com/uuid-rs/uuid/pull/788
* Reduce bitshifts in from_u64_pair by @KodrAus in https://github.com/uuid-rs/uuid/pull/790
=> prepare for 1.12.1 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
* Fix `wasm32` with `atomics` by @bushrat011899 in https://github.com/uuid-rs/uuid/pull/797
=> Prepare for 1.13.1 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/v1.13.1...main
=> Prepare for 1.13.2 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/v1.13.2...main
=> Prepare for 1.14.0 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/1.14.0...main
=> Prepare for 1.15.0 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/1.15.0...main
=> Prepare for 1.15.1 release

src/v8.rs
=> Mark `Uuid::new_v8` const

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/v1.15.1...main
=> Prepare for 1.16.0 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/v1.16.0...main
=> Prepare for 1.17.0 release

Cargo.toml, README.md, macros/Cargo.toml, rng/Cargo.toml, src/lib.rs
https://github.com/uuid-rs/uuid/compare/v1.18.0...main
=> Prepare for 1.18.0 release
