- src/lib.rs
Considering that the hyphenated format of UUIDs is the most common one, as far as I know, I think it's better for the `Display` implementation to output that format instead.
I've also replaced the `Debug` implementation, because reading `Uuid { bytes : [32, 46, 108, ...] }` in a log file isn't so nice.
I'll add a test for the `Debug` implementation if necessary.
> Modify Debug and Display implementations to use to_hyphenated_string()

- src/lib.rs
It is 16 octets but each octet takes two hex characters to represent, so the function returns
32 characters.
> Fix documentation of to_simple_string()

- Cargo.toml
- src/lib.rs
This PR brings support for `serde`. It can be optionally enabled to avoid the dependency on `serde` if it's not used. The cargo feature flag is called `serde`.
A `Uuid` is serialized to and deserialized from it's hyphenated string representation like the `rustc_serialize` implementation does. Additionally a `Uuid` can be deserialized from it's 16-bytes representation.
There are no tests for this functionality currently, should I add some tests using `serde_json` as dev-dependency for example?
> Add support for deserialization via serde

- Cargo.toml
Only a simple version update. No breakage expected because the feature `serde` wasn't released yet.
> Update dependency `serde`

- src/lib.rs
---
This allows `ParseError` to participate in `try!` in mixed company.
> ParseError: implement the ErrorTrait

- README.md
- src/lib.rs
The current readme file is sparse and forces users into the documentation for even the simplest use case.
This commit expands the readme with some of the basics from the documentation, providing a better first impression of the library and it's capabilities.
> Expand the README

- Cargo.toml
- src/lib.rs
This update isn't semver-compatible since it breaks users of `uuid` who use `serde = ^0.6.0`. Therefore we should raise the minior instead of patch I think. What is the common consensus in the rust ecosystem?
> Update dependency `serde` to version 0.7.0

- src/lib.rs
I thought it would make more sense to have `from_bytes` return a `Result` instead of an `Option`.
Let me know what you think!
[breaking-change]
> feat(from_bytes): return Result instead of Option

- src/lib.rs
Useful as it allows a UUID to be used as a key for a BTreeMap, which wasn't possible before.
This is accomplished by using the underlying byte array's builtin Ord/PartialOrd implementations.
> Implement `Ord` and `PartialOrd` for `Uuid`

- src/lib.rs
The `rand` feature, which was renamed to `v4`, was still mentioned in the documentation.  Update those references.
> lib: Change `rand` to `v4`

- src/lib.rs
They're not perfect yet, but add some examples, and fix some consistency issues
> Improve some docs

- src/serde.rs
Blocks https://github.com/servo/servo/pull/12898, because ipc-channel uses bincode, which doesn't use the default `deserialize`: https://github.com/TyOverby/bincode/blob/master/src/serde/reader.rs#L192.
With this change, the following test snippet can work:
```rust
extern crate bincode;
extern crate uuid;
extern crate serde;
#[cfg(test)]
mod tests {
use uuid::Uuid;
use bincode::serde::*;
use bincode::SizeLimit;
#[test]
fn it_works() {
let id = Uuid::new_v4();
let bytes = serialize(&id, SizeLimit::Infinite).unwrap();
let id_: Uuid = deserialize(&bytes).unwrap();
assert_eq!(id, id_);
}
}
```
> Fix for bincode deserialize

- src/lib.rs
With specific malformed inputs, like: `"F9168C5E-CEB2F4faaFB6BFF329BF39FA1E4"`, `parse_str` used to panic with:
```
"thread '<unnamed>' panicked at 'index out of bounds: the len is 16 but
the index is 16', src/lib.rs:658"
```
The problem was in the loop that processes input characters: The loop happily writes all valid characters that aren't group delimiters to a buffer. With some cleverly placed hyphens, it was possible to fool the loop into trying to write more bytes to the buffer than is possible.
This problem was found with cargo-fuzz.
> Fix an index out of bounds panic in parse_str

- Cargo.toml
- src/serde.rs
Deserialize and Visitor now requires a lifetime... just a small update to add this.
> Update to serde 1.0

- src/lib.rs
Valid UUIDs are always ascii so we can avoid doing the decoding unless
we encounter a byte that is not a valid character.
```
name                           orig ns/iter  new ns/iter  diff ns/iter   diff %  speedup
bench_parse                    1,832         1,407                -425  -23.20%   x 1.30
bench_parse_invalid_character  71            64                     -7   -9.86%   x 1.11
bench_parse_invalid_group_len  102           80                    -22  -21.57%   x 1.27
bench_parse_invalid_groups     123           100                   -23  -18.70%   x 1.23
bench_parse_invalid_len        2             2                       0    0.00%   x 1.00
bench_valid_hyphenated         116           96                    -20  -17.24%   x 1.21
bench_valid_short              98            78 …
```
> Avoid doing character decoding when parsing uuids

- src/serde.rs
... if the serializer supports it. Missed adding this in the previous PR
https://docs.rs/serde/1.0.8/serde/trait.Serializer.html#method.collect_str
> Try to avoid allocating a String when serializing

- src/lib.rs
It’s to avoid memory initialization before copying the digest.
> Eliminate a use of copy_memory

- Cargo.toml
- src/serde.rs
test_serialize_round_trip found in `rustc_serialize.rs`,  but not in serde.rs, add one.
> Add test serialize_round_trip of serde

- src/lib.rs
This change adds a `Uuid::as_fields()` method, which is to `from_fields()` as `as_bytes()` is to `from_bytes()`.  (I found myself wishing for such a method when writing code elsewhere to serialize a `Uuid` with Windows byte order, i.e. each field separately little-endian.)  I tried to add new unit tests as closely analogous to those for `as_bytes` as possible (e.g. checking that `as_fields()` and `from_fields()` round-trip properly).
> Add Uuid::as_fields() method

- Cargo.toml
- src/serde.rs
This uses the
[is_human_readable](https://github.com/serde-rs/serde/releases/tag/v1.0.16)
method added in serde 1.0.16 to serialize uuid's in a more compact
form if the serialized format does not need to be human readable.
This does not have an explicit test for `is_human_readable == false` since https://github.com/serde-rs/serde/issues/1065 has not been completed for serde_test so you may want to wait with merging. I have verified it manually though.
(Maybe?) related #90
> Serialize to binary if the serde format is not human readable

- Cargo.toml
- src/serde.rs
Ended up completing the compact/readable serde_test API so here are the
tests missing from https://github.com/rust-lang-nursery/uuid/pull/104.
I also replaced the `serde_json` roundtrip test with plain `assert_tokens`
tests which do essentially the same thing. I can re-add it if it seems
worthwhile to keep it though.
> Add tests for compact/readable representations

- .travis.yml
- Cargo.toml
- src/lib.rs
The `use_std` feature remains for backwards compatibility.
Fixes #107.
> Rename `use_std` feature to `std`

- CODE_OF_CONDUCT.md
- README.md
Adds the Contributor Covenant code of conduct and badges for the latest version on `crates.io`, gitter chat and travis links (we need to configure Travis for this project's new home).
> Add code of conduct and badges

- src/lib.rs
IntelliJ lints really help. 
its mostly replacing `try!(..)` with `?` and `assert!(..)` with `assert_eq!(..)` and `assert_ne!(..)`
> macro use cleanup

- Cargo.toml
- README.md
- src/lib.rs
Now routes to docs.rs instead of doc.rust-lang.org
closes #128
> fix documentation links

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/std_support.rs
> use std by default

- README.md
- src/lib.rs
References #132 
Fist beta release for 0.6.0. We will release a stable 0.6.0 either this week or next week once all bugs have been fixed or attended to.
> Release  for 0.6.0-beta

- src/lib.rs
* new_v1 now takes any implementor of UuidV1ClockSequence, instead of just UuidV1Context.
* UuidV1Context implements UuidV1ClockSequence, but ignores the `seconds` and `nanoseconds` arguments.
This takes a more conservative approach. No changes to the way UuidV1Context generates sequences, but now other people can implement their own clock-sequence generators.
The nice thing is that *I think* this is entirely backwards compatible (which means that this didn't need to block 1.0).
This is meant to address #106. It does not implement all the suggestions that it had, but it allows users to, and also allows us to add more implementations with different clock-sequence strategies in a backwards-compatible way.
> Add a new trait, `UuidV1ClockSequence` which defines the interface for generating clock sequences.

- Cargo.toml
> Update sha1 to 0.5

- .travis.yml
Specifically test against `rustc 1.18.0` so we know when we regress the minimum supported version. Personally, I'm ok with pushing the minimum version as a non-breaking change, but it's always good to know and communicate in the release notes.
> Add minimum supported rustc version

- Cargo.toml
- No changes that affect us, but keeping the crate updated.
> Update sha1 crate to 0.6.0

- Cargo.toml
- src/lib.rs
This adds a constructor that uses the explicit type `UuidBytes`.
The main difference between this constructor and `from_bytes` is that the length of `UuidBytes` is fixed at the correct length, so any use of `from_uuid_bytes` cannot fail. As such, instead of returning a `Result` it simply returns a `uuid`.
A secondary reason for this is that, if `const` functions ever move into nightly, this function would be an easy way to allow external consumers of this library to create `const` UUIDs.
If there are any other tests, or contribution guidelines that I've failed to include, please let me know.
> Add from_uuid_bytes

- Cargo.toml
addaecd0fc9a1dbb053420ff91ed61ec1fc31395
removed this feature, which was intentionally left deprecated for
backwards compatibility. This "cleanup" removed a deprecated feature
before any released version actually had the deprecation present.
Removing this feature makes it impossible for other crates to support
UUID 0.6 without dropping support for UUID 0.5 and earlier. This is a
major problem for crates like Diesel, which are post-1.0
> Bring back the renamed `use_std` feature for backwards compat

- Cargo.toml
- benches/parse_str.rs
- src/lib.rs
This implements `slog::Value` behind a feature-gate, allowing the use of `Uuid` in a key-value pair. Includes a test and bench.
> adds optional slog::Value impl

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug
- .github/ISSUE_TEMPLATE/feature
- .github/ISSUE_TEMPLATE/tracker
- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/release
- README.md
Issues:
[`/issues/new`]: Use the default issue template.
[`/issues/new?template=bug`]: Use the bug report template.
[`/issues/new?template=feature`]: Use the feature request template.
[`/issues/new?template=tracker`]: Use the tracker template. Only for us to use.
[`/issues/new`]: https://github.com/uuid-rs/uuid/issues/new
[`/issues/new?template=bug`]: https://github.com/uuid-rs/uuid/issues/new?template=bug
[`/issues/new?template=feature`]: https://github.com/uuid-rs/uuid/issues/new?template=feature
[`/issues/new?template=tracker`]: https://github.com/uuid-rs/uuid/issues/new?template=tracker
---
PRs:
[`/pulls/new`]: Use the default PR template.
[`/pulls/new?template=release`]: Use the release preparations template. Our own use only.
[`/pulls/new`]: https://github.com/uuid-rs/uuid/pulls/new …
> add issue and PR templates

- Cargo.toml
- src/lib.rs
- src/serde_support.rs
- src/std_support.rs
`uuid` now adds `cfg-if` as a dependency.  With this, `#[cfg(..)]` implementations are easier to understand, as they can be handled in a more logical view because the macro allows us to `if` statements to make the checks more rustic at the source level
Understanding feature gate implementation becomes easier.
The CI builds passing should be plenty.
#147
> Use cfg-if to create logical feature gate implementations

- src/lib.rs
Replace `uuid::copy_memory` with `<[_]>::copy_from_slice`
`core` already provides a good optimized version of `slice` copying function, so we dont need to create our own duplicate code.
Our tests and benchmarks are running good, other than one or two runs which suggest a 1-2 nanosecond slowdown.
#173
> Delete copy_memory function

- benches/parse_str.rs
- src/lib.rs
- src/serde.rs
Adds `Nil` variant to the `UuidVersion`.
`nil` `Uuid`, containing all zeros, is a valid `Uuid`, as per the specification. This will allow users doing pattern matching to explicitly check for it.
Updated `test_nil` to ensure that 
closes #133
supersedes #176
> Add Nil variant

- src/prelude.rs
Remove `ParseError` from the `prelude` reexports
`0.7` will rename `ParseError`, and `prelude` should only contain stable items, which will never altered in an unstable manner.
N/A
#166
> Remove ParseError from the prelude

- src/lib.rs
- src/prelude.rs
- src/v1.rs
* Move v1 impl into `uuid::v1`
* Rename `UuidV1ClockSequence` -> `UuidClockSequence`
* Rename `UuidV1Context` -> `UuidContext`
* Added `UuidClockSequence`, `UuidContext` to the prelude
Part of the great refactor effort
All tests passing, no new tests needed
#124
> Refactor v1 implementation

- src/v1.rs
unnecessary cfg_if if check causes compile error 
observed with no_std + `v1` feature environment
Squash bugs :man_shrugging: 
build uuid with `cargo build --no-default-features --features v1` with this change and without
N/A
> Fix v1 import of atomic module

- benches/parse_str.rs
- src/core_support.rs
- src/lib.rs
- src/prelude.rs
- src/serde_support.rs
- src/v1.rs
- src/v4.rs
- src/v5.rs
UuidVersion added back into the prelude, was accidently removed
n/a
n/a
closes #202
> fix prelude UuidVersion item missing

- src/lib.rs
make `UuidVersion` and `UuidVariant` explicitly repr(C) enums
Progressive change to allow creating C compatible interface
N/A
#159
> make UuidVersion and UuidVariant C enum

- Cargo.toml
cfg_if without an else block is not supported until 0.1.2, see https://github.com/alexcrichton/cfg-if/commit/8a594d0994b5c37f3cad035a6c76ae0105bce013
Fixes #205
> Fix minimum required cfg_if version

- src/adapter.rs
- src/lib.rs
* Add `adapter::UUID_HYPHENATED_LENGTH`, `adapter::UUID_SIMPLE_LENGTH` and `adapter::UUID_URN_LENGTH`
* Remove `::HYPHENATED_LENGTH` and `::SIMPLE_LENGTH`
Allow users to the adapter to determine the lengths to the adapters. Step 1 in the adapter refactor
All current tests passing
#124, #212
> provide adapter length constants

- src/lib.rs
- src/v3.rs
Signed-off-by: Hunar Roop Kahlon <hunar.roop@gmail.com>
Move v3 implementation to the v3 module
Part of the grand refactor
All tests, including v3 tests passing 
#124
> refactor v3 implementation

- Cargo.toml
- src/lib.rs
- src/u128_support.rs
allow support for `u128` <-> `Uuid`
As of `1.26.0` rust you can use `u128` in stable rust
added `test_from_u128` test function
#234
> backport u128 support

- Cargo.toml
New versions available of both `serde` and `serde_test`
`u128` support in `1.0.56` `serde`
tests pass
#239
> update serde and serde_test crates

- src/lib.rs
- src/prelude.rs
- src/u128_support.rs
* Change from `[u8; 16]` to `UuidBytes` across files
Consistency
All current tests pass
> use UuidBytes instead of [u8; 16]

- src/lib.rs
- src/v1.rs
Use 
```rust
#![deny(
missing_copy_implementations,
missing_debug_implementations,
missing_docs
)]
```
instead of
```rust
-#![deny(warnings)]
```
As rust adds new warnings, our crate may not build in the future, creating unnecessary breakage
current tests passing
> explicitly deny warnings

- src/lib.rs
- src/util/core_support.rs
- src/util/mod.rs
**I'm submitting a(n)** feature
Adds a `UuidLength` utility enum. Useful for parsing. The location is not final and may be moved around as we start using in the crate.
This is currently not used in the crate, however, future PRs are expected to rectify this.
Current parsing mechanism assumes only `Hyphenated`, `Simple`, `Urn` and `SIV` uuids exist. However this not true. This will help make parsers, especially external parsers for other formats 
No tests currently. However, when other parts use this enum they can update their tests to use this
#276
> add UuidLength enum

- Cargo.toml
**I'm submitting a(n)** removal
feature `use-std` was renamed earlier in #108 and brought back and marked deprecated in #158. Removing it now
#108, #158
> Remove deprecated "use-std"

- src/core_support.rs
- src/lib.rs
- src/std_support.rs
- src/v1.rs
**I'm submitting a(n)** feature, refactor
* Introduce a `::UuidError` type.
* Change signature of `::Uuid::from_fields`, `::Uuid::new_v1` and `::Uuid::from_bytes` to use the new error type.
This now splits the `Uuid` creation types into 3 categories:
* those which have no errors for creating
* those which throw errors based around parsing (currently `ParseError`)
* those which throw errors based around bytes (`UuidError`)
`ParseError` is oriented around parsing uuid strings. However, that error type does not bode well functions that are accepting bytes. 
All current tests pass with the signature change. No new tests added
closes #281
> introduce UuidError for general Uuid use

- src/parser/mod.rs
Make `fn`s in `::parser` module crate private
These are considered experimental, so exposing them is not the
best idea
> make the current 2 parser functions crate public

- src/adapter/core_support/mod.rs
- src/adapter/mod.rs
- src/core_support.rs
- src/lib.rs
- src/prelude.rs
- src/u128_support.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
It was discussed in the gitter chat that prefixing every data structure with `Uuid` is redundant.
> remove Uuid prefix

- src/adapter/mod.rs
- src/lib.rs
Fixes `const_fn` functions actually `const fn`
Incorrect behavior see #309
N/A
closes #309
> fix `const_fn` marked functions not being const for adapters

- Cargo.toml
- benches/format_str.rs
- benches/serde_support.rs
- src/adapter/core_support/mod.rs
- src/adapter/mod.rs
- src/lib.rs
- src/serde_support.rs
**I'm submitting a(n)** feature
Add encode_{lower,upper} to formatting adapters for core::fmt-less rendering.
These are noticably faster (20ns, ~50%) as they avoid all the virtual
call overhead of core::fmt/write! (etc.). This also improves the
performance of (human-readable) serde encoding, since that previously
went through core::fmt.
Benchmark results both with LTO and without including a comparison
against crates.io/crates/uuidtoa:
```
test lto_bench_encode_hyphen ... bench:          16 ns/iter (+/- 1)
test lto_bench_encode_simple ... bench:          14 ns/iter (+/- 1)
test lto_bench_encode_urn    ... bench:          18 ns/iter (+/- 2)
test lto_bench_hyphen        ... bench:          36 ns/iter (+/- 1)
test lto_bench_simple        ... bench:          33 ns/iter (+/- 7)
test …
```
> Add encode_{lower,upper} to formatting adapters for core::fmt-less rendering.

- src/prelude.rs
The `prelude` does not contain inlined items anymore
The doc links were directing the users to the prelude items instead
of the actual items
N/A
> don't inline the prelude items.

- Cargo.toml
- src/lib.rs
Fix the value of `#![doc(html_root_url)]` in `lib.rs`.
See also: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#crate-sets-html_root_url-attribute-c-html-root
> fix the value of html_root_url in lib.rs

- src/lib.rs
**I'm submitting a feature**
This PR adds little-endian constructors as well as a `to_bytes_le` and a `to_fields_le` method. I've also renamed the previous bytes methods and appended the be suffix for consistency while adding the previous function names as wrapper methods around those to not break things. All of this is personal preference of course so far so please point out changes you want to have with this.
Edit: I forgot to mention that the le methods use the `to_*` naming conventions instead of `as_*` since they aren't a free conversion and dont return a `&Bytes`
Issue #277.
Tested via doc-tests
#277
> Add little-endian functions

- src/builder.rs
- src/lib.rs
- src/prelude.rs
**I'm submitting a feature**
This PR implements a basic UuidBuilder that takes itself by `&mut` instead of `self` as shown in the issue #171 description.
Issue #171
Through Doctests
#171
> Add Uuid Builder

- .travis.yml
Remove the builds for 1.22.0 not testing slog. Was introduced to prevent failing builds since slog introduced a bump of MSRV to 1.26.0 which broke our builds on 1.22.0
slog has released 2.4.1, which lowered the MSRV back to 1.15.0+
Tests are passing. No new tests introduced.
closes #328
> remove slog test exclusion for 1.22.0 env

- Cargo.toml
- src/lib.rs
- src/winapi_support.rs
**I'm submitting a(n)** feature
Adds `guid` feature which is now used to enable windows GUID support.
`guid` is a better name for guid support than just `winapi`
No changes
#333, #336
> add guid feature

- Cargo.toml
This patch updates the `md5` dependency from 0.5 to 0.6. The API of the `md5` crate is not exposed in `uuid`, just used in one single method which uses it internally, so this is not a semver breaking change.
> Update md5 0.5 to 0.6

- .travis.yml
CI builds are failing because we are attempting to use `cargo build` for wasm builds. `cargo-web utility properly handles issues that are being caused
Failures while trying to pass #355 
Current builds build in CI
N/A
> try to get wasm builds running

- src/parser/core_support.rs
Use string instead of `str::Chars`
While working on `uuid_cli` I realized that when an invalid character was provided in a namespace uuid for v3 and v5 variants, the expected characters is shown as a numeric array instead of an array of chars. Not helpful for users. 
As its only a error message change, no tests needed
N/A
> fix parser::Error::InvalidCharacter Display message

- src/core_support.rs
- src/lib.rs
Use `fmt::LowerHex` as the base for `fmt::Debug`
#356 indicates that reading raw byte values for the uuid bytes is not easy for debugging purposes.
N/A
#356
> make Debug output for Uuid as hyphenated uuid instead of raw bytes

- benches/format_str.rs
- src/adapter/mod.rs
- src/lib.rs
Make optimized versions of encode* functions available.
Previously made crate public, allow faster than rust fmt conversion.
Bench tests show improvement. See #343 
closes #343
> enable the encode_{lower,upper} methods

- README.md
- README.tpl
The way the generation will work is that it will use the link according to local Cargo.toml uuid version. So hopefully it will always use the reference to the docs.rs uuid
The Uuid struct wasn't being linked.
> fix a tiny mistake in the README generation

- src/adapter/mod.rs
- src/lib.rs
`encode_{lower, upper}` tests were not enabled when we enabled the functions.
More tests
New tests enabled
> enable adapter tests for encode_{lower, upper}

- .travis.yml
- Cargo.toml
- src/lib.rs
**I'm submitting a(n)** refactor|removal
Removes the `u128` feature. `u128` related API is available as is now. Did not 
`2018` edition now supports `u128`s out of the box
Current tests should pass. No need for new tests
closes #366
> remove the u128 feature

- src/builder.rs
- src/lib.rs
- src/v1.rs
**I'm submitting a(n)** feature|refactor
Add `const fn` in a few more places than #389. Used `clippy` and its nursery lint to detect them.
More `const fn` the better. 
Current tests should pass. No new tests added
> Make functions that can be const, const

- src/adapter/core_support/mod.rs
I'm submitting a refactor of trait implementations for adapter traits
As all the trait implementations are the same across all adapters, they can be implemented using a single macro.
Reducing code duplication and improving transparency of intent.
As there are no code changes, this change is covered by existing tests
> Implementing adapter traits using macro

- src/lib.rs
- src/parser/core_support.rs
- src/parser/mod.rs
Allows for future parsing ability for the adapters.
This was a breaking change as such was needed to be added in 0.8.0`
Current tests should pass. No new tests introduced.
closes #370
> adjust ParseError for indicating if an urn format was expected

- src/lib.rs
**I'm submitting a(n)** removal
Removed `Uuid::from_random_bytes(crate::Bytes) -> Self`
`Uuid::from_random_bytes` was already deprecated. Time to remove.
All tests should pass. A test regarding the `Uuid::from_random_bytes` was removed.
N/A
> remove Uuid::from_random_bytes

- src/builder.rs
- src/lib.rs
- src/v3.rs
- src/v5.rs
**I'm submitting a(n)** removal
Removes `Uuid::set_variant` and `Uuid::set_version`
These methods were private and already `uuid::builder::Builder` was being recommended.
Current tests should pass.
N/A
> Remove the set_version and set_variant methods

- src/lib.rs
I'm submitting a small addition to the documentation for `Uuid::to_timestamp`.
The sentence explains what the timestamp number represents (100ns intervals since 1582-10-15). 
I think it's wise to include since this is not a common timestamp format in other contexts.
> add sentence to `Uuid::to_timestamp` docs specifying format

- README.md
The ignore made the code example non highlighted text. Looks way better with only "```rust"
Added code highlighting for Readme code example.
Text looked bad.
> Removed "ignore" from code example markup

- src/lib.rs
**I'm submitting a(n)** (bug fix|deprecation|feature|refactor|removal|other)
Remove the `#[repr(C)]` for `Variant` and `Version`.
These were added because uncertainty on whether the
C interface will be directly provided in the crate itself.
Since then I have resolved to use uuid-rs/xuuid.c instead.
No test changes are needed
N/A
> remove the #[repr(C) attributions

- .travis.yml
- Cargo.toml
Update rand to the next major version (0.7)
avoid rand duplication across ecosystem
`cargo test` locally works
> :arrow_up: rand

- src/lib.rs
- src/parser/core_support.rs
- src/parser/mod.rs
Renamed `uuid::parser::Expected` to `uuid::parser::ExpectedLength`
`Expected` was slightly ambiguous.
Current tests should pass as is. No new tests.
N/A
> Rename Expected to ExpectedLength

- Cargo.toml
- README.md
- src/lib.rs
- src/parser/error.rs
Closes #431 
[Changeset since the last release](https://github.com/uuid-rs/uuid/compare/0.7.4...master)
Includes:
- #427 
- #419 
- #424 
- #418 
- #413 
- #407 
- #404 
- #400 
- #399 
- #398 
- #397 
- #396 
- #394 
- #393 
- #390
- #389 
- #388 
I've also added some docs to the 128bit integer methods to clarify how they're different than `to_fields` (for consistency with other uuid libs in the wild).
> Prepare for 0.8.0 release

- .github/workflows/fmt.yml
- .travis.yml
Moves `cargo fmt` step to Github Actions
Overall Github Actions provide more flexibility for us. 
But since Actions are still in beta, starting with fmt is a relatively safe start
> GitHub actions/fmt

- .github/workflows/clippy.yml
- .travis.yml
- src/adapter/mod.rs
- src/builder/mod.rs
- src/parser/error.rs
- src/parser/mod.rs
- src/v1.rs
Moves clippy tests over to Github Actions
> Introduce Clippy Github Actions

- Cargo.toml
- README.md
- src/lib.rs
- src/v4.rs
Use `getrandom` crate directly instead of `rand` for generating UUIDs using v4.
Reduce the number of dependencies used by the crate.
Running the example in the README: 
- Before (10): c2-chacha, cfg-if, getrandom, libc, ppv-lite86, rand, rand_chacha, rand_core, rand_hc, wasi  
- After (4): cfg-if, getrandom, libc, wasi
`cargo test` locally and test usage in a simple program.
Wasn't sure whether I should bump the version here or not.
> Use getrandom crate for uuid

- src/winapi_support.rs
> make `Uuid::from_guid` infallible

- README.md
**I'm submitting a grammar fix for the README**
Previously, the README contained "They are particularly useful in distributed systems, *though can be used*..."
To a native speaker, this sounds a little strange, whereas "They are particularly useful in distributed systems, though **they** can be used..." is clearer and more grammatically correct.
I'd like to make the README easier to understand
I read it out loud and it sounded better and made more sense.
N/A
> Fix unspecified direct object in README

- bors.toml
I missed to do this while working on #487, as now appveyor has been unlinked
> remove appveyor from bors

- src/v4.rs
**I'm submitting a(n)** other - documentation improvement
The rand crate changed its trait names, so these docs were referencing a
trait that doesn't exist in the current version of rand. Change to be a
bit more vague to avoid this getting out of date again.
Also "use rand instead" wasn't very clear because "rand" doesn't contain
something clearly equivalent like `get_uuid_v4`. To be clearer, add a
reference to the `Builder::from_bytes` function in this crate.
It took me a few minutes to figure out what this documentation was saying, and I'd like to save someone else those few minutes in the future.
N/A
None
> Clarify documentation around the relation to the rand crate

- src/v4.rs
#447 changed from using `rand::thread_rng` to using `getrandom` in `Uuid::new_v4`. This also changed the return type from `Uuid` to `Result<Uuid, getrandom::Error>`. This PR reverts the signature to the simpler `new_v4() -> Uuid`.
This signature is much simpler to use, and avoids a breaking change. `getrandom` is _highly_ unlikely to fail, and previously we used `thread_rng` here, which also panics if it fails to initialize from the OS entropy source. If `getrandom` fails, it is highly unlikely that any program creating v4 UUIDs has any reasonable recovery other than to abort, as the system is in a broken state.
If users absolutely need to recover in this situation, they can call `getrandom` first themselves to make sure that their system is working, or …
> Un-breaking-change Uuid::new_v4

- .github/workflows/ci.yml
- .github/workflows/clippy.yml
- .github/workflows/fmt.yml
- Cargo.toml
- README.md
- README.tpl
Update getrandom to v0.2.0.
This raises the MSRV to getrandom's, 1.34.0.
Use the latest version of upstream.
N/A
- #475: It'd be great to have a new release that uses `getrandom` instead of `rand`, especially since a new version of `rand` is out as well. (NB: the change to `new_v4` from returning `Self` to returning `Result<Self, _>` is, of course, breaking, and will mean releasing the new version as `uuid:0.9`.)
- closes #494: the @dependabot-bot version of this PR. Failing due to not updating the MSRV.
> Update to getrandom:0.2.0

- src/serde_support.rs
**I'm submitting a** refactor
Improves the deserialization error message by including that a UUID was attempted to be parsed.
Before: `invalid length: expected one of [36, 32], found 11`
After: `UUID parsing failed: invalid length: expected one of [36, 32], found 11`
It was not easy to tell from the previous error message what went wrong when trying to deserialize a larger object containing a UUID.
I added a unit test.
Closes #499
> Improve deserialization error message

- src/lib.rs
As noted in #504, our description of the WebAssembly features isn’t quite accurate anymore now that we’ve shifted from `rand` to `getrandom`. In either case we enable the `js` feature of `getrandom` which just pulls in both `stdweb` and `js-sys` unconditionally.
r? @CAD97
> rework description of wasm crate features

- src/lib.rs
**I'm submitting a** feature.
Implement `AsRef<[u8]>` for `UUID`.
Open issue #472
All existing tests pass.
closes #472
> Add impl AsRef<[u8]> for Uuid

- src/adapter/mod.rs
**I'm submitting a** feature.
Trait implementations on the adapters:
* `From<Adapter> for Uuid`
* `AsRef<Uuid> for Adapter`
* `Borrow<Uuid> for Adapter`
An `Adapter::into_inner` method that takes self and returns a `Uuid`.
Open issue #482
All tests pass.
Closes #482
> Allow access of inner Uuid for adapters

- src/lib.rs
Previously, to_fields and to_fields_le used unsafe to convert a &[u8] into a &[u8; 8]. Now that we're only supporting Rust versions where TryInto is stable, we can use try_into().unwrap() instead, making uuid entirely safe Rust.
In release mode, the compiler detects that the slice will always be the correct size, so try_into can never fail. Thus, the unwrap
is optimized out and we end up with the exact same assembly as the unsafe block.
Godbolt output showing the resulting assembly: https://godbolt.org/z/nWxT6W
Makes UUID entirely safe Rust.
With this PR,
All existing tests pass. Doesn't add any new functionality, so that should be sufficient. Assuming the Godbolt test is consistent with what happens in the context of the larger crate, this shouldn't …
> Use TryInto to avoid unsafe.

- src/builder/mod.rs
- src/lib.rs
This PR resolves #517 by adding two methods:
`Uuid::from_u64_pair(high_bits, low_bits) -> Uuid`: Creates a UUID from two u64, the first being the MSBs, and the second, the LSBs.
`Uuid::as_u64_pair(&self) -> (u64, u64)`: Returns a pair of u64, the first being the MSBs, and the second, the LSBs.
> Added support for converting u64 pair into UUID and back

- Cargo.toml
- README.md
- src/lib.rs
I'm submitting a feature
The v3, v4, v5 features did not work on `wasm32-unknown-unknown` in a no_std context.
For v3 and v5, the `md5` and `sha1` crates are no_std if their default features are disabled, so they work on `wasm32-unknown-unknown`.
For v4, `getrandom` can work on any architecture if the root crate registers a custom implementation.
This is not a breaking change, as the other architectures (including `stdweb` and `wasm-bindgen`) are not impacted.
I wanted to use this crate (especially the v4 feature) on a `wasm32-unknown-unknown` context that does not have `stdweb` nor `wasm-bindgen`.
The test suite unfortunately does not run on `wasm32-unknown-unknown`.
The v3, v4, v5 features work properly, as I was able to use them from a dependent crate.
> Allow v3, v4, v5 features on wasm32-unknown-unknown

- src/lib.rs
**I'm submitting a(n)** other (documentation fix)
The current example at https://docs.rs/uuid/0.8.2/uuid/index.html#examples to generate a UUIDV4 currently does not compile, given that `Uuid` no longer implements `Try`.
This PR updates the example to match the one given in the README of this repo, along with enabling testing for it again to ensure it doesn't go out of date. I've run `cargo test --all-features` to ensure that the tests do indeed pass.
Finally, we also hide the configuration flags, `#[cfg(feature = "v4")]`, from the example, since it should not be copied by the user of the crate, if they wanted to use the example.
I was looking to generate a UUID V4 and unfortunately the examples in https://docs.rs/uuid/0.8.2/uuid/index.html#examples were out-of-date.
This enables the …
> Update Uuid::new_v4 documentation to reflect `Try` no longer being implemented

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/adapter/compact.rs
- src/lib.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
This PR does some more work on our CI to explicitly test wasm through Node and that we build for a proper no-std target. It also uses `cargo-hack` instead of manually listing out feature combinations to test.
> add more ci for wasm and embedded targets

- src/builder/mod.rs
- src/lib.rs
For:
- #406 
- #461 
- #462 
Adds some docs on whose endianness we're referring to in our `_le` suffixed methods. It's always independent of the endianness of the environment, and refers to the endianness of the fields themselves.
> Add more docs on endianness

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/v1.rs
For #469
This checks a few more features against a proper no-std target, to make sure we're not accidentally pulling in `std`.
It doesn't currently test `v4`, because it needs an ambient source of randomness. I _think_ that's possible to do with `getrandom`, but we also have other methods for constructing a random UUID without needing the `v4` feature explicitly.
> check more features in no-std

- src/v4.rs
Fixes a typo in V4.rs `retreive` -> `retrieve`.
> Fix typo in v4.rs

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/lib.rs
Follow up to #498
This adds support for the `zerocopy` library as an unstable feature. In order to build you'll need to enable the `zerocopy-unstable` feature as well as set a `RUSTFLAGS` cfg directly:
```
RUSTFLAGS="--cfg uuid_unstable"
```
Since we'll need to pull in new versions of `zerocopy` as they're released we'll bump it in minor releases of `uuid`, which may break consumers that opt-in until the new version of `zerocopy` propagates.
cc @mwanner @sivadeilra
> Add unstable zerocopy support

- Cargo.toml
- src/winapi_support.rs
Part of #537
In #336 we introduced conversions between Windows GUIDs and UUIDs. These didn't attempt to swap the ordering of the fields in any way. GUID specifies its fields as being in the native endianness (which for Windows is basically always little endian), while UUID requires them to be big endian. So we started flipping those fields coming from GUIDs in #345. Unfortunately, this seems like it was the wrong thing to do. All GUIDs I've been able to find already have the right ordering for UUIDs, so we've just been mangling them and losing the UUID version and variant.
This PR fixes that by removing the endianness conversion. We're going to be pulling this out into a separate crate before stabilizing so we can call out the change there. Anybody who actually does want to flip bytes …
> Don't flip GUID fields when converting to UUID

- src/v1.rs
The name `to_timestamp` is a bit inconsistent with our other methods that pluck individual values from the UUID without re-interpreting it. This PR renames it to `get_timestamp` so it's consistent with `get_version` and `get_variant`.
> Rename to_timestamp to get_timestamp

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- benches/v4.rs
- src/lib.rs
- src/rng.rs
- src/v4.rs
Closes #529 
This adds a `fast-rng` feature that can be used to generate `v4` UUIDs much faster than `getrandom` (which just falls back to OS APIs).
The quality of the random data is no less suitable with `fast-rng` than the fallback. It just requires more dependencies to build, and some users of `uuid` are very dependency-averse.
> Add support for using rand for rng

- README.md
- benches/v4.rs
- src/fmt.rs
- src/lib.rs
- src/parser.rs
- src/serde_support.rs
Closes #534, #457, #532
This PR implements `TryFrom<&str> for Uuid`. I didn't add `String` or `&String` at this stage. They may become useful in generic contexts, but at least for `String` I don't think you'd want to lose the owned data if converting into a `Uuid` doesn't succeed.
It also ensures the `serde` readable format is able to handle the fixed-size tuples the non-readable format uses.
> More serde and parsing impls

- src/rng.rs
- src/v1.rs
Closes #432 
This adds a `new_random` constructor to `Context` that seeds it with a random initial value when the `rng` or `fast-rng` features are also available.
It also stashes the last timestamp we saw and only increments the counter if it matches.
> Only increment v1 context when the seconds component matches

- .github/workflows/ci.yml
Just to make sure `uuid` isn't implicitly tied to LE architectures.
> Add a big endian target to CI

- macros/src/lib.rs
- shared/error.rs
- shared/parser.rs
- src/parser.rs
- tests/ui/compile_fail/invalid_parse.rs
- tests/ui/compile_fail/invalid_parse.stderr
Fixed an bug where the `uuid!("")` macro would point to the wrong characters when using the `urn:uuid:` prefix or wrapping with the curly braces (`"{...}"`).
none
> Fixed `uuid!("")` macro diagnostics when using `urn:uuid` prefix.

- shared/parser.rs
- src/fmt.rs
- src/parser.rs
I'm submitting a refactor
This PR improves the performance of `Uuid::{try_parse, parse_str}` and `{Simple, Hyphenated, Braced, Urn}::{encode_lower, encode_upper}`
| bench                   | before | after     |
| ----------------------- | ------ | --------- |
| encode_hyphen           | 25 ns  | **15 ns** |
| encode_simple           | 23 ns  | **15 ns** |
| encode_urn              | 29 ns  | **16 ns** |
| hyphenated              | 43 ns  | 37 ns     |
| simple                  | 39 ns  | 32 ns     |
| urn                     | 46 ns  | 37 ns     |
| parse_invalid_character | 72 ns  | 63 ns     |
| parse_invalid_group_len | 81 ns  | 73 ns     |
| parse_invalid_groups    | 94 ns  | 90 ns     |
| parse_invalid_len       | 88 ns  | 86 ns     |
| parse_nil               | 46 ns  | **26 ns** | …
> Improve `try_parse` and `encode` performance

- shared/error.rs
- shared/parser.rs
- src/fmt.rs
cc @Nugine @QnnOkabayashi 
This just adds some inline comments to the parser implementation so it's easier for new contributors to follow.
> Add some inline comments to the new parser impl

- shared/error.rs
- src/builder.rs
- src/external/mod.rs
- src/external/serde_support.rs
- src/lib.rs
- src/parser.rs
Closes #557 
It turns out that serializing as a `[u8; 16]` is not really a better default than `&[u8]`, so this PR reverts it in favor of the current stable implementation.
> Revert default compact serialization

- shared/parser.rs
- src/builder.rs
- src/fmt.rs
- src/lib.rs
- src/v1.rs
For #553 
This is just a final pass over our crate docs, fixing up any little things I notice along the way.
> some small doc cleanups

- Cargo.toml
- README.md
- examples/uuid_macro.rs
- macros/src/lib.rs
- src/lib.rs
- src/macros.rs
- tests/macros.rs
I'm submitting a feature
https://github.com/uuid-rs/uuid/issues/556#issuecomment-959352417
resolves #556
> Provide uuid macro without dependencies

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
- src/macros.rs
Part of #113 
This PR gets us ready for an alpha release of `uuid` `1.0` that can be used to ensure everything is good in downstream consumers. Ideally we won't make any API changes before actually stabilizing `1.0` proper, but some things may come up that need additional breaking alpha releases.
This release includes a _huge_ amount of work from a lot of contributors. I'll try call out breakage here as well as in release notes once we're ready to merge so everyone knows what to expect.
https://github.com/uuid-rs/uuid/compare/0.8.2...main
- #510 
- #482 
- #511 
- #507 
- #518 
- #519 
- #512 
- #520 
- #521 
- #525 
- #526 
- #527 
- #528 
- #535 
- #536 
- #539 
- #538 
- #540 
- #541 
- #542 
- #544 
- #545 
- #546 
- #543 
- #547 
- #548 
- #549 
- #550 
- #552 
- #554 
- #558 
- #560 …
> Prepare for 1.0.0-alpha.1 release

- src/lib.rs
I'm resolving #580 .
See issue
#580
> Add Uuid::into_bytes(self)

- Cargo.toml
- macros/Cargo.toml
- tests/macros.rs
For #585 
These tests will only ever make sense on `nightly` compilers, since in other cases we won't be able to produce subspans (we can't currently get them anyways, but that might be fixable).
> Only check diagnostics output on nightly

- Cargo.toml
- src/builder.rs
- src/lib.rs
- src/macros.rs
- src/md5.rs
- src/rng.rs
- src/sha1.rs
- src/v1.rs
- src/v3.rs
- src/v5.rs
This affects #588: We've renamed the `zerocopy-unstable` feature to simply `zerocopy`. You still need the `uuid_unstable` RUSTFLAGS cfg to use it, but this avoids starting to accumulate a lot of dead features as they stabilize. That way if we promote `zerocopy` to a stable feature users don't need to change what features they enable, they can simply stop setting `uuid_unstable`.
This also renames all of our internal optional dependencies so that they discourage direct use by end-users. Otherwise we'd be stuck in a place where changes to what optional dependencies we use could break any dependents that set those features. Some optional dependencies are pure implementation details that end users shouldn't be tinkering with directly, but some of them aren't. So this tries to distinguish them …
> Rework optional dependencies to discourage direct use as Cargo features

- Cargo.toml
- src/sha1.rs
Closes #582 
Follow-up for #581 
This PR follows the crate renaming of `sha1` so that we default to the zero-dependency `sha1_smol` crate, but support a `fast-sha1` feature that pulls in the rust-crypto `sha1` crate with its `asm` feature. This follows the same approach we've used for RNG where users get a small footprint by default, but can pull in more specialized implementations if they want to.
> Use the sha1_smol library for SHA1

- macros/src/lib.rs
- tests/ui/compile_fail/invalid_parse.stderr
Closes #585 
It turns out the span attached to our token stream doesn't cover the actual content we want to subspan. This fixes that up by threading our parsed literal to errors to report diagnostics on.
> Use the parsed literal as the span source for errors

- src/builder.rs
`& 0x1f` sets the left three bits to zero, but `| 0xe0` sets them back to one. The AND (`&`) can therefore be removed as unnecessary. This is similar to how in the NCS case there is only an AND (no OR).
- 0x1f = 00011111
- 0xe0 = 11100000
> Remove unnecessary AND

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
Closes #113
Well, here we are :tada: This PR officially stabilizes the `uuid` crate's API and semantics. There's some future work around support for v6-v8 UUIDs, but those will be done in a backwards compatible fashion. I haven't bumped our MSRV or anything here, since we can do that along with edition upgrades in minor releases as per our MSRV policy.
We've been sitting on this alpha release for a while now so I think it's time to commit.
cc @kinggoesgaming
> Prepare for 1.0.0 release

- src/error.rs
I just spotted https://github.com/diesel-rs/diesel/pull/3143 run through, where they make some assertions based on the shape of `uuid::Error`'s display implementation. I think it's safe to treat `Display` impls as public API and avoid churning them. I didn't drop any comment on the adapter types that format UUIDs themselves since I think that's pretty clear that the format is part of their contract.
> note that the Error display impl is public API

- src/lib.rs
The link to the `to_simple()` and `to_urn()` methods in the `Uuid` structure documentation were broken.
None
> Fixed documentation link

- src/lib.rs
**I'm submitting a feature**
This adds the `to_bytes_le` method to `Uuid`. It returns the bytes of the UUID in little-endian order.
#462
> Add to_bytes_le method

- src/fmt.rs
Some doc links were broken (referencing `adapter`). This PR fixes those links and changes some links (in the same file) to shortcut reference links.
> Fix some doc links

- .github/workflows/ci.yml
- .rustfmt.toml
- examples/windows_guid.rs
- macros/src/lib.rs
- macros/src/parser.rs
- src/builder.rs
- src/external/arbitrary_support.rs
- src/external/serde_support.rs
- src/fmt.rs
- src/lib.rs
- src/md5.rs
- src/parser.rs
- src/v1.rs
- src/v3.rs
- src/v5.rs
**I'm submitting a refactor**
Formatting the codebase a bit by following `cargo fmt --check` recommendations
#609
> formatting changes

- .github/workflows/ci.yml
- Cargo.toml
- src/builder.rs
- src/lib.rs
- src/parser.rs
- src/rng.rs
- src/timestamp.rs
- src/v1.rs
- src/v4.rs
- src/v6.rs
- src/v7.rs
- src/v8.rs
**I'm submitting a feature** 
This addresses all requested features in #523
Adds v6, v7 and v8 features and modules. 
It also adds a Timestamp::now()  which does what you might expect and uses std::time::SystemTime. 
I added some basic tests for each, but they could certainly use more tests and more eyes. 
This refactors Timestamp to make it more generally applicable to all (time based) UUIDs. 
It also breaks context/sequence out of Timestamp, since that only applies to v1 and v6.  
This changes the API for v1 and v6, to require a Context to be supplied at creation. 
Updates the crate to Edition 2021
Removes a dependency on atomic and instead uses std::sync::atomic since it now supports the necessary types.  
#523
> refactors Timestamp, Context and ClockSequence, and adds UUIDS v6, v7, v8

- Cargo.toml
- examples/windows_guid.rs
**I'm submitting a(n)** (deprecation|refactor|removal)
Migrate from `winapi` to `windows-rs` for the following:
1. [Winapi is no longer actively](https://github.com/retep998/winapi-rs/issues/867 ) maintained (last commit was 9 months ago as of now and 2nd last around 2 years ago) compared to last commit to [windows-rs ](https://github.com/microsoft/windows-rs)as of few days ago.
2. [windows-rs](https://github.com/microsoft/windows-rs) is the official Rust crate for Windows by Microsoft and is supposed to be providing a natural and idiomatic way for Rust developers to call Windows APIs. Some crates like [socket2](https://github.com/rust-lang/socket2) have already migrated to it.
None
I f-ed the commit history somehow
The main issue was:
I just saw the build error `"windows v0.39.0" cannot …
> migrate from winapi to windows_sys in examples

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/macros.rs
- src/md5.rs
- src/rng.rs
- src/sha1.rs
- src/timestamp.rs
- src/v7.rs
This PR implements `Timestamp::now()` in WebAssembly when the `js` feature is enabled. When `js` is not enabled, the `SystemTime` type is used instead.
> Implement now in wasm

- .github/workflows/ci.yml
- src/builder.rs
- src/lib.rs
- src/timestamp.rs
Part of #523 
This PR gates the code implementing the draft version 6 to version 8 support behind our RUSTFLAGS cfg. They’re probably safe now since they haven’t changed recently, but are still technically in draft and have changed in the past.
> hide draft versions behind the unstable cfg

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
- src/v7.rs
This includes:
- #630
- #631
- #633
- #610
- #616
- #611
- #626
- #628
- #625
The MSRV has been bumped to `1.57.0`.
> Prepare for 1.2.0 release

- src/builder.rs
- src/v1.rs
Closes #635 
This fixes an accidental breaking API change in a lost import from the `v1` module.
> Fix up lost re-export of v1 Timestamp

- .github/workflows/ci.yml
- Cargo.toml
This PR removes the need to split Windows builds from the others and unpins the `arbitrary` crate that was previously done for MSRV reasons.
> CI Cleanups

- src/lib.rs
Closes #643 #644 
This was erroneously added in `1.2.0`, but shouldn't be necessary at all.
Thanks @lulf for the report!
> Remove extern crate alloc

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
> Prepare for 1.2.2 release

- src/external/arbitrary_support.rs
This makes generating from non-arbitrary crates work much better, as they know how many bytes are needed to arbitrary-generate an uuid.
Without `Arbitrary::size_hint` implemented, the default implementation returns `(0, None)`, which means that `Uuid` needs any number of bytes between `0` and `usize::MAX` to generate.
In turn, when trying to use it from `bolero::gen_arbitrary()`, generation ended up very slow, because bolero was generating much more data than actually required.
With this change, `uuid` claims that it always needs exactly 16 bytes to generate an `Uuid`, which is true and makes `bolero::gen_arbitrary` generate exactly 16 bytes for it.
- https://github.com/camshaft/bolero/issues/111
> implement Arbitrary::size_hint

- src/fmt.rs
- src/lib.rs
Closes #652 
The main use for alternate formatting is to pretty-print complex structs. It's surprising to have UUIDs change their format when pretty-printing, so this PR just always uses hyphenated formatting.
> Always use hyphenated format regardless of flags

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
Includes:
- #656 
- #657 
- #658 
- #654 
The main change to call out here is that the alternate debug format for `Uuid` (that is, `{:#?}`) is now the same hyphenated format used in regular debug.
> Prepare for 1.3.0 release

- src/lib.rs
**I'm submitting an** improvement
Implement `as_u128` and `to_u128_le` using `u128::from_be_bytes` and `u128::from_le_bytes`, respectively.
This is faster because it avoids the array indexing and shift operations. Depending on the machine endianess, `from_be_bytes`/`from_le_bytes` will either be a no-op or a single [`intrinsics::bswap`](https://doc.rust-lang.org/std/intrinsics/fn.bswap.html) (which on most platforms is just a couple of instructions). It's also a simpler implementation that simply relies on the std u128 functions.
In my informal testing, this was consistently about 3x faster.
```rust
use std::hint::black_box;
use std::time::Instant;
use uuid::Uuid;
fn main() {
let uuid = Uuid::new_v4();
let bytes = uuid.as_bytes();
macro_rules! time {
($name:literal, $expr:expr) => {
let …
```
> Faster as_u128 and to_u128_le

- .github/workflows/ci.yml
- src/timestamp.rs
The `Timestamp::to_unix` method has been deprecated for some time now. I'd like to remove it entirely in a future release. I can't find any actual usages of it, since the method was never useful, so in a `2.x` release of `uuid` it will disappear. Note that since the plan is for `1.x` to re-export `2.x` that means this method will vanish in some future minor release of `1.x`. We don't want to do this often, but the alternative of letting multiple versions of the `Uuid` type float around is worse than having a single deprecated and useless method disappear.
> Hard deprecate Timestamp::to_unix_nanos

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
* Use sha hash for checkout action and remove others by @KodrAus in https://github.com/uuid-rs/uuid/pull/671
* Hard deprecate Timestamp::to_unix_nanos by @KodrAus in https://github.com/uuid-rs/uuid/pull/673
> Prepare for 1.3.3 release

- .cargo/config
- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/timestamp.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
- src/v6.rs
- src/v7.rs
- src/v8.rs
@sunfishcode added `wasm32-wasi` support in #477, but somewhere along the way it appears to have been broken or dropped. Thankfully, the reason for the breakage doesn't appear too deep: the `wasm-bindgen` support was enabled for all `wasm32` architectures, rather than just the `wasm32-unknown-unknown` target triple that [`wasm-bindgen` supports](https://rustwasm.github.io/wasm-bindgen/reference/rust-targets.html).
This PR fixes the `cfg` expressions for `wasm-bindgen`-specific code so that they no longer catch `wasm32-wasi`, and now `wasm32-wasi` just works 🎉
To guard against future breakage, I added some `wasm32-wasi` testing infrastructure. A new CI target modeled on the `wasm-bindgen` target tests the `wasm32-wasi` implementation against `wasmtime`. Since test runners can't be …
> Add `wasm32-wasi` support with tests

- src/timestamp.rs
Fix: https://github.com/uuid-rs/uuid/issues/681
> fix: keep the order when filling random bytes

- Cargo.toml
- src/lib.rs
- src/timestamp.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
- src/v6.rs
- src/v7.rs
- src/v8.rs
Fixes #687 by replacing
```rust
target = "wasm32-unknown-unknown"
```
with
```rust
all(target_arch = "wasm32", target_vendor = "unknown", target_os = "unknown")
```
> Fixed wasm tests not running due to incorrect attribute target

- src/external/arbitrary_support.rs
- src/external/borsh_support.rs
- src/lib.rs
- src/timestamp.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
- src/v6.rs
- src/v7.rs
- src/v8.rs
- tests/smoke-test/src/main.rs
Closes #680 
This PR makes `Timestamp` conversions explicitly wrap rather than panic on overflow.
I've also fixed up a warning in `arbitrary`, and removed a random `dbg!` statement that shouldn't be there.
> Fix some timestamp generation

- src/lib.rs
- src/macros.rs
- tests/ui/compile_pass/hygiene.rs
> Fix macro hygiene

- src/builder.rs
- src/lib.rs
[As seen in this playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=caa6418cf6c80c8ccbf8c5521fccb5b4), neither `from_bytes` nor `from_bytes_ref` are currently inlined by the compiler even though they are `const`, resulting in less efficient generated code for these trivial functions, even with Thin LTO enabled. There's a slippery slope here for what counts as "trivial", but the functions that *do not change representations* are a pretty safe bet.
(I didn't include the Builder versions of the same functions, because the *next* thing you do with a Builder is likely to be a function call anyway, but it could go either way.)
> Add #[inline] for Uuid::from_bytes[_ref] and Uuid::{as,into}_bytes

- examples/random_uuid.rs
- examples/sortable_uuid.rs
This PR just prints UUIDs in examples when they run so you can both tell that the example ran, and have a look at the result it produced.
> Print uuids in examples

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
* Fix macro hygiene by @teohhanhui in https://github.com/uuid-rs/uuid/pull/694
* Add #[inline] for Uuid::from_bytes[_ref] and Uuid::{as,into}_bytes by @jrose-signal in https://github.com/uuid-rs/uuid/pull/693
* Print uuids in examples by @KodrAus in https://github.com/uuid-rs/uuid/pull/697
> Prepare for 1.4.1 release

- src/fmt.rs
This PR adds the implementation of `From<Uuid> for String` under the "std" feature flag. The motivation for this is that it allows Uuids to be easily converted to a string when using crates like sqlx where it utilize the `Into` and `From` traits for conversions.
> Add impl From<Uuid> for String under the std feature flag

- CONTRIBUTING.md
For #702 
It was pointed out that our `CONTRIBUTING` docs refer to the old issue templates, which have since been removed.
> Remove dead link to templates

- src/timestamp.rs
- src/v1.rs
- src/v6.rs
As pointed out in the original issue, the implementation of `ClockSequence` for `Context` incorrectly wrapped after `0x3ffe` instead of `0x3fff`.  Fixes #702.
> make ClockSequence wrap correctly

- Cargo.toml
- README.md
This PR removes some old references to our MSRV as pointed out in https://github.com/uuid-rs/uuid/pull/673#issuecomment-1679763874
Instead, we can track it using the `rust-version` field in our `Cargo.toml`.
> Track MSRV in Cargo.toml

- .github/workflows/ci.yml
- src/timestamp.rs
This PR performs some housekeeping on our CI by replacing MIPS with Miri for testing any endian-dependent code and adding `clippy` too so we can keep up with changing lints better.
> Replace MIPS with Miri and add clippy to CI

- src/v6.rs
Fix links to `struct Timestamp`, `trait ClockSequence`, and `struct Context` under `timestamp` module.
Hello, I am new to GitHub work flow.
Is there any question / anything that needs to change again in this PR ?
Or should I first send review request to any of the maintainers of this repository ?
I don't find any contribution guide here, I don't know what else  I can do,
thanks
> doc: fix links in v6 module

- .github/workflows/ci.yml
- Cargo.toml
- benches/v7.rs
- examples/sortable_uuid.rs
- src/builder.rs
- src/lib.rs
- src/macros.rs
- src/timestamp.rs
Closes #523
This PR lets you use the `v6`, `v7`, and `v8` variants without also having to set the `UUID_UNSTABLE` environment variable. It means it's now feasible for libraries to use these formats, and for applications to simplify their builds.
I've added a benchmark for `v4` vs `v7` that users can run if they're interested in the potential impact of switching from fully random to sortable UUIDs.
> Stabilize UUIDv6-v8 support

- Cargo.toml
- src/lib.rs
- src/md5.rs
Part of #672 
This PR makes use of the `dep:` and `?/` features of Cargo to avoid creating public features of private dependencies, and to only enable features of dependencies when they're already present.
> Make use of newer Cargo features for specifying dependencies

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
* Add missing test for invalid parse_str by @CXWorks in https://github.com/uuid-rs/uuid/pull/723
* Upgrade borsh unstable dependency to v1.0 and make it stable by @bgeron in https://github.com/uuid-rs/uuid/pull/724
* Reduce the package size of uuid by @KodrAus in https://github.com/uuid-rs/uuid/pull/726
* Make use of newer Cargo features for specifying dependencies by @KodrAus in https://github.com/uuid-rs/uuid/pull/727
* @CXWorks made their first contribution in https://github.com/uuid-rs/uuid/pull/723
* @bgeron made their first contribution in https://github.com/uuid-rs/uuid/pull/724
> Prepare for 1.7.0 release

- src/parser.rs
Just a small tweak in the rustdocs; `or` -> `of`
> docs: fix small spelling mistake

- src/external/serde_support.rs
- src/lib.rs
- src/parser.rs
**I'm submitting a** feature
Description
========
Adds the ability to serialize a `Uuid` as a `Simple`/`Urn`/`Braced`. `Uuid::parse_str` deserialize them correctly, but `Uuid` is always serialized as `Hyphenated`. Users would be able to decide which format to serialize to after this PR.
Example:
```rust
#[derive(serde_derive::Serialize)]
struct Struct {
// This will be serialize as uuid::fmt::Simple
#[serde(serialize_with = "uuid::serde::simple")]
id: uuid::Uuid,
}
```
Tests
========
3 new tests for the feature were added.
crate::external::serde_support::serde_tests::test_serialize_as_simple
crate::external::serde_support::serde_tests::test_serialize_as_braced
crate::external::serde_support::serde_tests::test_serialize_as_urn
Related Issue(s)
========
- …
> serde serialize_with support

- Cargo.toml
When setting the `js` feature, `uuid` would previously pull in all of `wasm-bindgen` even when targeting a native build:
```
❯ cargo tree -p uuid --target aarch64-apple-darwin --no-default-features --features js
uuid v1.7.0 (/Users/emilk/code/forks/uuid)
└── wasm-bindgen v0.2.91
├── cfg-if v1.0.0
└── wasm-bindgen-macro v0.2.91 (proc-macro)
├── quote v1.0.35
│   └── proc-macro2 v1.0.78
│       └── unicode-ident v1.0.12
└── wasm-bindgen-macro-support v0.2.91
├── proc-macro2 v1.0.78 (*)
├── quote v1.0.35 (*)
├── syn v2.0.48
│   ├── proc-macro2 v1.0.78 (*)
│   ├── quote v1.0.35 (*)
│   └── unicode-ident v1.0.12
├── wasm-bindgen-backend v0.2.91
│   ├── bumpalo v3.14.0
│   ├── log v0.4.20
│   ├── once_cell v1.19.0
│   ├── proc-macro2 v1.0.78 (*)
│   ├── quote v1.0.35 (*)
│   ├── syn v2.0.48 (*) …
```
> Only add `wasm-bindgen` as a dependency on `wasm32-unknown-unknown`

- src/lib.rs
Added the following AsRef impl:
```rust
impl AsRef<Uuid> for Uuid {
#[inline]
fn as_ref(&self) -> &Uuid {
self
}
}
```
Having this means you can write code like this that accepts `Braced`, `Hyphenated`, `Simple`, `Urn`, or `Uuid`:
```rust
fn find_with_uuid(uuid: impl AsRef<Uuid>) 
```
For completeness this is technical possible currently using something like this:
```rust
fn find_with_uuid(uuid: impl Borrow<Uuid>) 
```
However (and I am open to being corrected on this) my understanding is this is much less idiomatic then `AsRef<T>`. My understanding after reading over the std docs and some discussion online is: 
`Borrow<T>` implies a function doesn't care if it gets `T`, `&T`, or `&mut T`. 
`AsRef<T>` implies a function doesn't care what it gets as long as it can be represented as `&T`. …
> impl AsRef<Uuid> for Uuid

- README.md
This PR just adds a link to the draft spec for v6 to v8 UUIDs. It's a rewrite of RFC4122 that's more consistent and modern in its recommendations for other versions too.
> Add v6 to v8 draft link to README

- macros/src/error.rs
- src/error.rs
- src/external/serde_support.rs
- src/external/slog_support.rs
- src/lib.rs
- src/parser.rs
- src/v1.rs
- src/v6.rs
- tests/ui/compile_pass/hygiene.rs
Closes #648 
This PR adds a `Uuid::get_node_id` method that returns `Some([a, b, c, d, e, f])` for V1 and V6 UUIDs, and `None` for others. It can help support conversion between V1 and V6 UUIDs.
I've also just fixed up some new warnings along the way.
> Add a get_node_id method for v1 and v6 UUIDs

- Cargo.toml
- src/lib.rs
The `zerocopy` update is a breaking change, but it's breaking an unstable dependency, so this makes sure we stay current with whatever version a consumer would be expecting to use.
> Update atomic and zerocopy to latest

- Cargo.toml
While I volunteered when the original request for volunteers was made, I never ended up actually doing anything in uuid-rs, so I don't think I belong in the authors line.
> Remove myself from the authors line in Cargo.toml

- macros/Cargo.toml
Hi! While scraping crates.io I've found `uuid-macro-internal` to be missing the repository field, making it difficult for users and automated tools to find out about the repository. This PR fixes it.
> Add repository field to uuid-macro-internal crate

- CONTRIBUTING.md
- README.md
- src/builder.rs
- src/lib.rs
- src/timestamp.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
- src/v6.rs
- src/v7.rs
- src/v8.rs
Hey!
Please welcome my first contribution here. The draft RFC is finally not draft anymore, but the old RFC is obsolete now.
I had my eyes on this for weeks, and the time has come to create the PR-s :)
---
**The changes are purely documental, there are no code changes.**
> update docs to updated RFC (from 4122 to 9562)

- src/builder.rs
- src/lib.rs
- src/rng.rs
- src/timestamp.rs
- src/v1.rs
- src/v4.rs
- src/v6.rs
- src/v7.rs
For #717
This PR sketches out a solution to make the v7 support respect the input counter, while retaining existing semantics around filling with random data. It requires a bit of fudgery to keep compatibility with existing APIs, but I think the overall solution works out ok. I need to actually fill it all in fully and then explore ways to better integrate the existing `Timestamp` API, which may involve deprecating bits.
The gist of it is to add a `usable_bits` method to `ClockSequence`, so it can tell how many bits a given counter occupies. The UUID constructor can then do appropriate shifts and fill the rest with random bytes. That way a caller creating a v7 UUID can decide how many bits to dedicate to sequencing and how many to randomness.
As part of this PR I'm expecting to find some …
> Support counters in v7 UUIDs

- .github/workflows/ci.yml
- src/timestamp.rs
In particular, this makes sure our BE tests cover all the version features.
> Expand miri tests to cover all features

- src/lib.rs
- src/timestamp.rs
- src/v7.rs
We can generalize the `impl ClockSequence<Output = u16>` APIs to `impl ClockSequence<Output = impl Into<u128>>` without major breakage so don't need to introduce new APIs for them. The `Timestamp::from_unix_time` API is new, so we can generalize it too before we release it.
> Clean up new Timestamp APIs

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
* Add a get_node_id method for v1 and v6 UUIDs by @KodrAus in https://github.com/uuid-rs/uuid/pull/748
* Update atomic and zerocopy to latest by @KodrAus in https://github.com/uuid-rs/uuid/pull/750
* Add repository field to uuid-macro-internal crate by @paolobarbolini in https://github.com/uuid-rs/uuid/pull/752
* update docs to updated RFC (from 4122 to 9562) by @Mikopet in https://github.com/uuid-rs/uuid/pull/753
* Support counters in v7 UUIDs by @KodrAus in https://github.com/uuid-rs/uuid/pull/755
> Prepare for 1.9.0 release

- Cargo.toml
- src/timestamp.rs
We previously would take the global lock when getting the number of bits the counter occupies in `Uuid::now_v7()`, despite this value being a constant.
As expected, it does reduce the cost of `Uuid::now_v7()`. On my M1 MacBook Pro:
Before:
```
test now_v7            ... bench:          61.51 ns/iter (+/- 0.83)
```
After:
```
test now_v7            ... bench:          55.67 ns/iter (+/- 2.43)
```
> Avoid taking the shared lock when getting usable bits in Uuid::now_v7

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
* Add an example of generating bulk v7 UUIDs by @KodrAus in https://github.com/uuid-rs/uuid/pull/761
* Avoid taking the shared lock when getting usable bits in Uuid::now_v7 by @KodrAus in https://github.com/uuid-rs/uuid/pull/762
> Prepare for 1.9.1 release

- src/macros.rs
The code below works when the user doesn't enable `macro-diagnostics` feature.
It's not possible to convert the value of identifier into a string literal at compile time, but is there another way we can go about this so we can give more details when this feature is enabled. 
If not, we can just paste the same code inside the macro where macro-diagnostics is enabled so that at least there wouldn't be a compile time error.
```rust
($uuid:ident) => {{
const OUTPUT: $crate::Uuid = match $crate::Uuid::try_parse($uuid) {
$crate::__macro_support::Ok(u) => u,
$crate::__macro_support::Err(_) => panic!("invalid UUID"),
};
OUTPUT
}};
```
Closes #756
> Use const identifier in uuid macro

- src/builder.rs
- src/lib.rs
- src/timestamp.rs
- src/v1.rs
- src/v6.rs
This PR builds off #754, just deprecating and renaming `Timestamp` functions that refer to RFC4122 by name. I've opted not to rename any enum variants so that we can keep derived `PartialEq` implementations that work in `const`s.
> Rename most methods referring to RFC4122

- Cargo.toml
- README.md
- macros/Cargo.toml
- src/lib.rs
* Use const identifier in uuid macro by @Vrajs16 in https://github.com/uuid-rs/uuid/pull/764
* Rename most methods referring to RFC4122 by @KodrAus in https://github.com/uuid-rs/uuid/pull/765
* @Vrajs16 made their first contribution in https://github.com/uuid-rs/uuid/pull/764
> prepare for 1.10.0 release

- src/error.rs
- src/external/arbitrary_support.rs
- src/external/serde_support.rs
- src/lib.rs
- src/non_nil.rs
- src/timestamp.rs
- src/v7.rs
Follow-up to #770 
This PR just fills in a few final bits for the `NonNilUuid` type before we stabilize it.
> Finalize `NonNilUuid`

- README.md
This isn't something we're actively using, so I'll simplify the readme down by removing it.
> Remove fossa integration from readme

- src/v5.rs
They're correct for [`Uuid::new_v3`](https://docs.rs/uuid/1.12.0/uuid/struct.Uuid.html#method.new_v3) but not for [`Uuid::new_v5`](https://docs.rs/uuid/1.12.0/uuid/struct.Uuid.html#method.new_v5).
> Fix links to namespaces in documentation

- src/builder.rs
use inherent to_be_bytes and to_le_bytes methods, rather than re-implementing them with lots of bitshifts
> use inherent to_be_bytes and to_le_bytes methods

- Cargo.toml
- src/lib.rs
- src/rng.rs
For #792 
This PR updates our version of `getrandom` to `0.3` and `rand` to `0.9`. It is a **potentially breaking change** for the following users:
1. Those in no-std environments enabling the `rng` feature (probably via `v4` or `v7`) and using `getrandom`'s APIs to configure a source of randomness on those platforms
2. Those in `wasm32-unknown-unknown` also using `getrandom`'s APIs to configure a source of randomness
If you're in WebAssembly and using the `js` feature, everything should still work. We've kept this behavior by vendoring in `getrandom`'s web-based backend.
If you're broken by this change, the current fix is to use [the `Builder`](https://docs.rs/uuid/latest/uuid/struct.Builder.html) instead. I'd be open to exploring other alternatives for these users, such as a pluggable …
> Update `getrandom` to `0.3` and `rand` to `0.9`

- Cargo.toml
- README.md
- macros/Cargo.toml
- rng/Cargo.toml
- src/lib.rs
This release updates our version of `getrandom` to `0.3` and `rand` to `0.9`. It is a **potentially breaking change** for the following users:
1. Those in no-std environments enabling the `rng` feature (probably via `v4` or `v7`) and using `getrandom`'s APIs to configure a source of randomness on those platforms. These users can upgrade their version of `getrandom` and follow its new docs on configuring a backend.
2. Those in `wasm32-unknown-unknown` enabling the `rng` feature as above, but without also using the `js` feature. These users can upgrade their version of `getrandom` as above, and also enable the `rng-getrandom` or `rng-rand` feature of `uuid` to force it to be used.
If you're on `wasm32-unknown-unknown` and using the `js` feature, you shouldn't see any breakage. We've kept …
> Prepare for 1.13.0 release

- .github/workflows/ci.yml
- Cargo.toml
- src/rng.rs
- Fixes #796
- Include `js_sys` explicitly when enabling the `js` feature on `wasm32` when compiling with the `atomics` `target_feature` enabled.
- Fix possibly outdated code from vendoring
- `js_sys` was already in the dependency graph due to `wasm-bindgen`, it just needed to be exposed when compiling under the conditions described in the attached issue.
- This is not a breaking change and could be published as 1.13.1 to fix 1.13.0 failing to compile in the aforementioned conditions.
> Fix `wasm32` with `atomics`

- README.md
- src/lib.rs
- src/rng.rs
For #802 
If you're compiling on `wasm32-unknown-unknown` without the `js` feature, and without `rng-getrandom` we won't have any random backend available and will fail to compile with a wall of unhelpful errors.
This PR adds a note to enable one of the appropriate features to specify the source of randomness.
> Add a compile_error when no source of randomness is available on wasm32-unknown-unknown

- src/fmt.rs
- src/parser.rs
- src/rng.rs
My specific use case is that I want to take a `Uuid` in `Simple` form as a query parameter and track it with a [signal](https://docs.rs/leptos_router/latest/leptos_router/hooks/fn.query_signal.html) while using Leptos. I don't want to accept other forms of `Uuid` in the query parameter, and when I update the parameter myself, I want the `Simple` form to show up in the browser's address bar. Using the `FromStr` and `Display` impls of `Uuid` won't get me what I want.
You could argue that this is more an issue with the Leptos query signal API, but I think it's sensible enough and I suspect this is not the only case wherein someone might want to restrict their string representation of a `Uuid` to a single format.
What I've submitted here is just a naive implementation of the desired traits. …
> Add FromStr impls to the fmt structs

- src/non_nil.rs
`NonNilUuid` currently has an automatic `Debug` trait implementation, resulting in an output that is not very useful:
```
NonNilUuid(1512366075204170929049582354406559215)
```
This PR adds a manual implementation of the `Debug` trait that properly formats the uuid, matching that of the `Uuid` type.
> Add a manual `Debug` implementation for NonNilUUid

- benches/v7.rs
- src/timestamp.rs
Closes #767
This PR refactors our `V7Context` type to support timestamps of varying precision. It can be used to improve the sortability of UUIDs in distributed systems by trading some entropy for wider timestamps.
I've also added support for shifting timestamps by some specified amount in applications that want to obfuscate the time a UUID was actually generated.
Still to do:
> Support higher precision, shiftable timestamps in V7 UUIDs

- src/timestamp.rs
Follow-up to #809
This PR just ensures that we don't accidentally overflow any values when constructing v7 UUIDs. Our behavior at the edges is to saturate rather than wrap, but we're free to pick whatever semantics we like here. This is really just closing a completeness hole rather than addressing any real use-cases.
> Guarantee v7 timestamp will never overflow

- src/parser.rs
It's directly ported to `TryFrom<&str>`, but makes writing some macros a lot easier.
> Added convenience implementation TryFrom<String> for std

- .github/workflows/ci.yml
- .github/workflows/outdated.yml
Looks like the OSX runners are ARM-based now
> Update OSX builds to arm

- src/lib.rs
My attempt to solve #775.
I am not sure about the following two things:
- If I imported core::hash::{Hash, Hasher} in an appropriate style.
- If the other derive(Hash) should also be removed.
> Replace derive(Hash) with manual impl in Uuid

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/rng.rs
- src/timestamp.rs
- src/v1.rs
- src/v3.rs
- src/v4.rs
- src/v5.rs
- src/v6.rs
- src/v7.rs
- src/v8.rs
`uuid` has support for `no_std`, and support for `wasm32-unknown-unknown`, but it currently _doesn't_ have support for the alternative `wasm32v1-none`. Attempting to compile `uuid` with the `v4` and `js` features on `wasm32v1-none` causes a compilation error due to `getrandom`.
Based on [`wasm32v1-none`](https://doc.rust-lang.org/beta/rustc/platform-support/wasm32v1-none.html#conditionally-compiling-code) and [`wasm32-unknown-unknown`](https://doc.rust-lang.org/beta/rustc/platform-support/wasm32-unknown-unknown.html#conditionally-compiling-code) documentation, and [this compilation failure condition](https://github.com/rust-random/getrandom/blob/2cf460252aaa897453801965e3e7c1cbf301d04d/src/backends.rs#L170) in `getrandom`, the configuration condition `uuid` should use for possibly-web …
> Add `wasm32v1-none` Support

- macros/src/parser.rs
- src/parser.rs
This lint is proving to be quite tedious to fix, but thankfully we don't seem to have too many instances of it to worry about here in `uuid`.
> Fix up mismatched_lifetime_syntaxes lint

- src/builder.rs
- src/error.rs
- src/parser.rs
- src/timestamp.rs
Follow-up to #835
This PR just wraps the error type in our `TryFrom` impl so that we can fail under other circumstances if we need.
> Wrap the error type used in time conversions

- Cargo.toml
- src/builder.rs
- src/fmt.rs
- src/lib.rs
- src/macros.rs
Re-working of #833 
This PR takes the work by @joshlf and re-gates `zeropcopy` support behind a feature flag since we can't publicly depend on its unstable API yet. To make it easier for us to use `zerocopy` or some standard subset of its functionality in the future, I've just wrapped up the few calls we make to its macros into `transmute`s when `zerocopy` is unavailable, and `zerocopy` calls when it is. This is still a nice step forward for the library, because we test `zerocopy` in CI, and so any attempt at an invalid transmute in the code will at least be caught there (and hopefully by `miri` too).
> Unsafe cleanup

- Cargo.toml
- README.md
- macros/Cargo.toml
- rng/Cargo.toml
- src/lib.rs
https://github.com/uuid-rs/uuid/compare/v1.18.0...main
> Prepare for 1.18.1 release

- Cargo.toml
- src/external/serde_support.rs
[serde_core](https://crates.io/crates/serde_core) has just been released. Crates that don't depend on serde derive macros should use it instead of `serde`, as it speeds up compile times by having the build for the crate itself be independent from `serde-derive` (in case it were to be enabled by some other crate). See the serde_core docs for more info.
On my Ryzen 5 5500U, the clean release build time for just `uuid` in a project containing `uuid` with the `serde` feature enabled, and `serde` with the `derive` feature enabled, went from 7.15s to 3.45s.
> Switch serde dependency to serde_core
